# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: William O'Beirne
email: wbobeirne@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, I'm William O'Beirne. Professional developer, amateur designer,
  aspiring bass player, and fake adult.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wbobeirne.github.io/" # the base hostname & protocol for your site
jsext: ".js"

# Collections
collections:
  work:
    output: true

# Build settings
markdown: kramdown
exclude:
  - node_modules
sass:
  sass_dir: _sass
