/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BioRouteImport } from './routes/bio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkChar123ProjectIdChar125RouteImport } from './routes/work/{-$projectId}'

const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BioRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkChar123ProjectIdChar125Route =
  WorkChar123ProjectIdChar125RouteImport.update({
    id: '/work/{-$projectId}',
    path: '/work/{-$projectId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bio': typeof BioRoute
  '/blog': typeof BlogRoute
  '/work/{-$projectId}': typeof WorkChar123ProjectIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bio': typeof BioRoute
  '/blog': typeof BlogRoute
  '/work/{-$projectId}': typeof WorkChar123ProjectIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bio': typeof BioRoute
  '/blog': typeof BlogRoute
  '/work/{-$projectId}': typeof WorkChar123ProjectIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bio' | '/blog' | '/work/{-$projectId}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bio' | '/blog' | '/work/{-$projectId}'
  id: '__root__' | '/' | '/bio' | '/blog' | '/work/{-$projectId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BioRoute: typeof BioRoute
  BlogRoute: typeof BlogRoute
  WorkChar123ProjectIdChar125Route: typeof WorkChar123ProjectIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/{-$projectId}': {
      id: '/work/{-$projectId}'
      path: '/work/{-$projectId}'
      fullPath: '/work/{-$projectId}'
      preLoaderRoute: typeof WorkChar123ProjectIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BioRoute: BioRoute,
  BlogRoute: BlogRoute,
  WorkChar123ProjectIdChar125Route: WorkChar123ProjectIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
